version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: reservation-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reservation_db
    ports:
      - "3308:3306"
    volumes:
      - ./reservation_db.sql:/docker-entrypoint-initdb.d/reservation_db.sql

  reservation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation-service
    depends_on:
      - mysql-db
    ports:
      - "8083:8083"
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/reservation_db
      DB_USERNAME: root
      DB_PASSWORD: root
